[package]
name = "wasm-webtools"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.9.2"
wasm-bindgen = "0.2"
getrandom = { version = "0.3", features = ["wasm_js"] }

